version: '3'

services:
  web:
    build: ./web
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
#    volumes:
#      - ${DB_PATH_HOST}:/var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always

    ports:
      - 6080:8080